---

# first upgrade and reboot hypervisors one at a time
- hosts: 'hypervisors'
  serial: 1
  tasks:
   - name: apk update
     raw: apk update
     changed_when: false

   - name: apk upgrade
     raw: apk upgrade
     register: upgrade_result
     changed_when: "'Upgrading' in upgrade_result.stdout"

   - name: reboot
     shell: "reboot"
     async: 1
     poll: 0
     when: "'Upgrading' in upgrade_result.stdout"

   - name: wait for reboot to complete
     wait_for_connection:
      connect_timeout: 20
      sleep: 2
      delay: 2
      timeout: 300
     when: "'Upgrading' in upgrade_result.stdout"

# gather all facts
- hosts: 'alpine_common'
  tasks: []

# now upgrade and reboot the rest of the infrastructure at random
- hosts: 'alpine_common'
  any_errors_fatal: false
  order: shuffle
  serial: 4
  tasks:
   - name: configure repos
     template:
      src: ../../../roles/alpine_common/templates/repositories
      dest: /etc/apk/repositories
      owner: root
      group: root
      mode: '0644'

   - name: apk update
     raw: apk update
     changed_when: false

   - name: apk upgrade
     raw: apk upgrade
     register: upgrade_result
     changed_when: "'Upgrading' in upgrade_result.stdout"

   - name: reboot
     shell: "reboot"
     async: 1
     poll: 0
     when: "'Upgrading' in upgrade_result.stdout"

   - name: wait for reboot to complete
     wait_for_connection:
      connect_timeout: 20
      sleep: 2
      delay: 2
      timeout: 300
     when: "'Upgrading' in upgrade_result.stdout"
