---

- name: install role packages
  package: name=bridge,bonding,haveged,telegraf,lm-sensors state=present

- name: start and enable haveged
  service:
   name: haveged
   enabled: true
   state: started

- name: land shell config
  template:
   src: color_prompt.sh
   dest: /etc/profile.d/color_prompt.sh
   owner: root
   group: root
   mode: '0644'

- name: configure telegraf
  template:
   src: telegraf.conf
   dest: /etc/telegraf.conf
   owner: root
   group: root
   mode: '0644'
  notify: restart telegraf

- name: start and enable telegraf
  service:
   name: telegraf
   enabled: true
   state: started

- name: land kernel modules
  template:
   src: modules
   dest: /etc/modules
   owner: root
   group: root
   mode: '0644'
  register: modprobe

- name: remove systelcssafsd
  file:
   path: /etc/sysctl.d/local.conf
   state: absent

- name: land sysctls
  template:
   src: supermicro_x7_x8_x9.conf
   dest: /etc/sysctl.d/supermicro_x7_x8_x9.conf
   owner: root
   group: root
   mode: '0644'
  register: sysctl

- name: configure kernel ulimits
  lineinfile:
   regexp: '^rc_ulimit='
   line: 'rc_ulimit="-n 65536"'
   path: /etc/rc.conf
  register: ulimit

- name: configure network interfaces
  template:
   src: interfaces
   dest: /etc/network/interfaces
   owner: root
   group: root
   mode: '0644'
  when: bond
  register: interfaces

- name: reboot
  shell: "reboot"
  async: 1
  poll: 0
  when: 'sysctl.changed or ulimit.changed or interfaces.changed or modprobe.changed'

- name: wait for reboot to complete
  wait_for_connection:
   connect_timeout: 20
   sleep: 2
   delay: 2
   timeout: 300
  when: 'sysctl.changed or ulimit.changed or interfaces.changed or modprobe.changed'
