---

- name: install role packages
  package: name=etcd,etcd-ctl state=present

- name: pip install boto3 for s3
  pip: name=boto3 state=latest

- name: retrieve all certs
  aws_s3:
   s3_url: '{{ s3_url }}'
   bucket: etcd
   object: '/{{ item }}'
   dest: '/etc/etcd/{{ item }}'
   mode: get
   overwrite: different
   validate_certs: false
   aws_access_key: "{{ lookup ('env', 'AWS_ACCESS_KEY') }}"
   aws_secret_key: "{{ lookup ('env', 'AWS_SECRET_KEY') }}"
  with_items:
   - "ca-key.pem"
   - "ca.pem"
   - "{{ static_address }}-key.pem"
   - "{{ static_address }}.pem"
  register: pull_certs
  until: pull_certs is not failed

- name: land healthcheck
  template:
   src: healthcheck.sh
   dest: /root/healthcheck.sh
   owner: root
   group: root
   mode: '0755'

- name: configure etcd conf.yml
  template:
   src: conf.yml
   dest: /etc/etcd/conf.yml
   owner: root
   group: root
   mode: '0644'
  notify: restart etcd

- name: start and enable etcd
  service:
   name: etcd
   enabled: true
   state: started
